### ISSUE TITLE
Wrong bit fields in lis3dh_temp_cfg_reg_t?

### ISSUE THREAD

**Issue by andreika-git** [STMicroelectronics/lis3dh-pid#2]
The order of TEMP and ADC fields is swapped in the lis3dh_temp_cfg_reg_t struct:

![image](https://github.com/STMicroelectronics/lis3dh-pid/assets/15104768/f0aa2849-6f34-4213-baec-022df87696bf)

![image](https://github.com/STMicroelectronics/lis3dh-pid/assets/15104768/1e7856b2-e49f-46a4-94e7-ed93c3ef34d8)

**Comment by avisconti** [comment]
Addressed by 7aa7400

**Comment by avisconti** [comment]
Thanks @andreika-git for discovering the typo.
